### ISSUE TITLE
Save files not converting

### ISSUE THREAD

**Issue by novasaurusrexx** [cgen-tools/save-converter#1]
Hello!  When I try and enter the file seen here below into the save converter, I get an error message saying that the file is not in the Aug 10 format.  Which as far as I know, it should be as that's the release it is coming from.  It ends up not letting the file convert.  Thanks in advance for the help, you guys all rock! 

[Nightcats.csv](https://github.com/cgen-tools/save-converter/files/10104803/Nightcats.csv)
[Nightclan.txt](https://github.com/cgen-tools/save-converter/files/10104804/Nightclan.txt)

**Comment by larkgz** [comment]
Thanks! I’ve pushed some fixes and the conversion should work now.

However, it looks like there’s a Clan-gen bug that will make patrols and some moon-skips crash if using an old `clan.txt`. Luckily, I found a workaround. After converting, save and then relaunch the game. Alternatively, you can add a single extra blank line to `Nightclan.txt`.
